version: '3.7'

services:
  db:
    image: postgres
    restart: always
    container_name: db
    ports: 
        - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes: 
        - ./.postgres:/var/lib/postgresql/data
  web:
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes: 
    data: